export const ADD_DRAGGABLE = 'add_draggable'
export const REMOVE_DRAGGABLE = 'remove_draggable'
export const REMOVE_ALL_DRAGGABLES = 'remove_all_draggables'
export const SELECT_CATEGORY = 'select_category'
export const FETCH_IMAGES_REQUEST = 'fetch_images_request'
export const FETCH_IMAGES_SUCCESS = 'fetch_images_success'
export const FETCH_IMAGES_FAILURE = 'fetch_images_failure'
export const FETCH_IMAGES_RESPONSE = 'fetch_images_response'
