# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release to testflight"
  lane :beta do
    increment_build_number(xcodeproj: "abaCards.xcodeproj")
    match(type: 'appstore') # makes sure signing is good for deploy
    build_app(scheme: "abaCards")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    clean_build_artifacts
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "abaCards.xcodeproj")
    match(type: 'appstore') # makes sure signing is good for deploy
    build_app(scheme: "abaCards")
    upload_to_app_store(
      skip_waiting_for_build_processing: true
    )
    clean_build_artifacts
  end
end
